# Module 1: Finding your way around the data

These notebooks grew out of our team's work at the 2026 ESICM Digital Critical Care Datathon. This revised exercise uses **invented records and invented concept IDs**, so you can run it without access to AmsterdamUMCdb. The data is deliberately small and includes mistakes worth investigating.

By the end, you should be able to find a variable, check its units and coverage, and explain why a plausible query may still identify the wrong patients.

You will read short SQL queries and change a few values. If notebooks are new to you, start with [Colab's introduction](https://colab.research.google.com/notebooks/intro.ipynb). The [AmsterdamUMCdb setup guide](https://github.com/AmsterdamUMC/AmsterdamUMCdb/blob/master/bigquery/getting_started_v2.ipynb) describes access to the real database. Dataset names and access arrangements will need checking at the next event.

The helper creates a local database and translates the displayed BigQuery SQL for local execution. That lets us test the lessons without claiming a new BigQuery run. Its source is in `datathon_prep/` in this repository.

In [1]:
# Install the teaching helpers if this is a fresh Colab session.
# The revision is pinned so these notebooks and their helpers stay together.
import importlib.util
import subprocess
import sys

HELPER_REVISION = "3b43b2311ae1734dcf384df8150cb83787a9beb5"
if importlib.util.find_spec("datathon_prep") is None:
    subprocess.check_call([
        sys.executable, "-m", "pip", "install", "-q",
        "git+https://github.com/ReginaldCal/Digital-Critical-Care-Datathon-Prep.git@" + HELPER_REVISION
    ])

import pandas as pd
from IPython.display import display
from datathon_prep import Demo, Pipeline, Rules, FEATURES

demo = Demo()
print("Synthetic teaching data only. No patient database connection is made.")

Synthetic teaching data only. No patient database connection is made.


## Start with the tables

In SQL, `SELECT` chooses columns, `FROM` identifies a table, and `WHERE` filters rows. `GROUP BY` collects rows for a summary such as a count. `JOIN` links tables using a stated relationship.

Do not assume that a table name guarantees useful content. During the datathon, the available visit and procedure information changed. Check the version you have.

In [2]:
demo.connection.execute("""
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'source' ORDER BY table_name
""").fetchdf()

,table_name
0,concept
1,condition_occurrence
2,death
3,device_exposure
4,drug_exposure
5,fluid_coverage
6,followup
7,measurement
8,visit_occurrence


In [3]:
demo.connection.execute("""
SELECT column_name, data_type FROM information_schema.columns
WHERE table_schema = 'source' AND table_name = 'measurement'
ORDER BY ordinal_position
""").fetchdf()

,column_name,data_type
0,measurement_id,BIGINT
1,person_id,BIGINT
2,visit_occurrence_id,BIGINT
3,measurement_datetime,TIMESTAMP
4,measurement_concept_id,BIGINT
5,value_as_number,DOUBLE
6,unit_source_value,VARCHAR


## Find a concept, then check whether it is recorded

In OMOP, standard concept IDs have shared meanings across databases. Local concepts, mapping choices and recording coverage can differ. Our `Synthetic` vocabulary is invented for this exercise and must never be copied into a real-data query.

Search the dictionary by name, inspect the meaning and units, and then count the matching records. Similar names do not guarantee interchangeable measurements: set and measured values, specimen types and devices can matter.

In [4]:
search_term = 'fio2'
concepts = demo.table('source.concept')
display(concepts[concepts.concept_name.str.contains(search_term, case=False, regex=False)])

demo.query("""
SELECT c.concept_id, c.concept_name, m.unit_source_value,
       COUNT(*) AS measurements, COUNT(DISTINCT m.person_id) AS people,
       MIN(m.value_as_number) AS minimum, MAX(m.value_as_number) AS maximum
FROM source.measurement m
JOIN source.concept c ON c.concept_id = m.measurement_concept_id
WHERE m.measurement_concept_id = 990001
GROUP BY c.concept_id, c.concept_name, m.unit_source_value
ORDER BY c.concept_id, m.unit_source_value
""")

,concept_id,concept_name,domain_id,vocabulary_id
0,990001,fio2,Measurement,Synthetic


,concept_id,concept_name,unit_source_value,measurements,people,minimum,maximum
0,990001,fio2,fraction,175,12,0.35,1.0


A low patient count does not make a variable irrelevant: it may identify a rare treatment. Counts describe coverage; clinical meaning determines whether the variable belongs in your definition.

Look at a few ordered records before choosing a transformation. Missing units need investigation. A percent sign is not, by itself, evidence that a value is wrong.

In [5]:
demo.query("""
SELECT person_id, visit_occurrence_id, measurement_datetime,
       value_as_number, unit_source_value
FROM source.measurement WHERE measurement_concept_id = 990001
ORDER BY person_id, visit_occurrence_id, measurement_datetime, measurement_id
LIMIT 12
""")

,person_id,visit_occurrence_id,measurement_datetime,value_as_number,unit_source_value
0,1,101,2026-01-01 00:00:00,0.6,fraction
1,1,101,2026-01-01 04:00:00,0.6,fraction
2,1,101,2026-01-01 08:00:00,0.6,fraction
3,1,101,2026-01-01 12:00:00,0.6,fraction
4,1,101,2026-01-01 16:00:00,0.6,fraction
5,1,101,2026-01-01 20:00:00,0.6,fraction
6,1,101,2026-01-02 00:00:00,0.4,fraction
7,1,101,2026-01-02 04:00:00,0.4,fraction
8,1,101,2026-01-02 08:00:00,0.4,fraction
9,1,101,2026-01-02 12:00:00,0.4,fraction


## 1. Normalise units before applying thresholds

A FiO₂ of `1.0` in fraction units means 100%, not 1%. Checking the raw number against a percentage threshold would admit it incorrectly. Here the units tell us how to convert. Unrecognised units become missing and remain available for review.

In [6]:
unit_example = pd.DataFrame({
    'raw': [0.4, 40, 1.0, 40], 'unit': ['fraction', '%', 'fraction', None]
})
unit_example['percent'] = [
    value * 100 if unit == 'fraction' else value if unit == '%' else float('nan')
    for value, unit in zip(unit_example.raw, unit_example.unit)
]
unit_example['meets_fio2_threshold'] = unit_example.percent.between(21, 50)
unit_example

,raw,unit,percent,meets_fio2_threshold
0,0.4,fraction,40.0,True
1,40.0,%,40.0,True
2,1.0,fraction,100.0,False
3,40.0,None,NaN,False


## 2. Link measurements to an admission

One person can have several ICU stays. A patient-level join can mix those stays even when the SQL runs successfully. Keep an admission identifier throughout the analysis.

The helper checks for duplicate identifiers and overlapping admissions before linking by person and time. When a measurement carries a visit ID, it must agree with the time interval. Boundary times use `[admission start, admission end)` to avoid attaching a record to two adjacent stays.

In [7]:
plan = Pipeline(prefix='discovery')
demo.validate_source()
demo.query(plan.admissions())
demo.query(plan.measurements())
demo.query("""
SELECT visit_occurrence_id, person_id, admission_start, admission_end
FROM work.discovery_admissions WHERE person_id = 1 ORDER BY admission_start
""")

,visit_occurrence_id,person_id,admission_start,admission_end
0,101,1,2026-01-01,2026-01-06
1,102,1,2026-01-11,2026-01-16


## 3. Define co-occurrence explicitly

Finding PEEP and tidal volume somewhere in a patient's history is not the same as finding them together. The next query requires readings within 30 minutes in the same admission. It also requires a synthetic record confirming invasive support.

The time window is an exercise assumption. With real data, validate both the measurement pairing and the invasive-support evidence. PEEP, tidal volume and FiO₂ alone do not establish that an endotracheal tube is present.

In [8]:
sql = plan.episodes()
print(sql)
demo.query(sql)
demo.table('work.discovery_episodes')

CREATE TABLE `work.discovery_episodes` AS
WITH paired AS (
  SELECT DISTINCT p.admission_id, p.person_id, p.measurement_datetime AS ts
  FROM `work.discovery_measurements` p
  JOIN `work.discovery_measurements` t ON t.admission_id = p.admission_id
   AND t.measurement_concept_id IN (990003)
   AND ABS(TIMESTAMP_DIFF(t.measurement_datetime, p.measurement_datetime, SECOND)) <= 1800
  WHERE p.measurement_concept_id IN (990002)
    AND LOWER(TRIM(p.unit_source_value)) = 'cmh2o' AND p.value_as_number BETWEEN 0 AND 30
    AND LOWER(TRIM(t.unit_source_value)) = 'ml' AND t.value_as_number BETWEEN 50 AND 2000
    -- Synthetic invasive-support record confirms the candidate measurement pair.
    AND EXISTS (
      SELECT 1 FROM `source.device_exposure` d
      WHERE d.person_id = p.person_id AND d.device_concept_id IN (990200)
        AND p.measurement_datetime >= d.device_exposure_start_datetime
        AND p.measurement_datetime < d.device_exposure_end_datetime
        AND t.measurement_datetim

,admission_id,person_id,episode_number,episode_start,episode_end,marker_count
0,501,5,1.0,2026-01-01 00:00:00,2026-01-03 00:00:00,13
1,601,6,1.0,2026-01-01 00:00:00,2026-01-03 00:00:00,13
2,1201,12,1.0,2026-01-01 00:00:00,2026-01-03 00:00:00,13
3,201,2,2.0,2026-01-03 12:00:00,2026-01-04 08:00:00,6
4,102,1,1.0,2026-01-11 00:00:00,2026-01-13 00:00:00,13
5,301,3,1.0,2026-01-01 00:00:00,2026-01-03 00:00:00,13
6,201,2,1.0,2026-01-01 00:00:00,2026-01-03 00:00:00,13
7,1101,11,1.0,2026-01-01 00:00:00,2026-01-03 00:00:00,13
8,801,8,1.0,2026-01-01 00:00:00,2026-01-03 00:00:00,13
9,101,1,1.0,2026-01-01 00:00:00,2026-01-03 00:00:00,13


The fixture includes a patient with ventilator-like measurements but no invasive-support confirmation. That patient should not enter the confirmed candidate episodes.

The six-hour gap rule is retained from the historical analysis as a teaching example. A short interruption or an extubation followed by rapid reintubation may be missed. A long recording gap may split continuous treatment. Episode boundaries inferred this way are proxies.

In [9]:
demo.query("""
SELECT COUNT(*) AS episodes_without_support_confirmation
FROM work.discovery_episodes WHERE person_id = 9
""")

,episodes_without_support_confirmation
0,0


## 4. Distinguish volumes, rates and counters

These three numbers cannot be summed in the same way:

| Record | Meaning | What is needed |
|---|---|---|
| Incremental volume, mL | Volume recorded for an interval | Verify units, coverage and no overlap before summing |
| Rate, mL/hour | A setting or rate over time | Establish duration and whether it is prescribed or delivered |
| Cumulative counter, mL | Total since a device-specific starting point | Establish baseline and verified resets before differencing |

The official 2026 dictionary lists ultrafiltration **set** CVVH with both `ml/uur` and `ml` units. We no longer describe that concept as universally safe to sum. The example below illustrates a counter with a known zero baseline and one verified reset.

In [10]:
from datathon_prep.demo import cumulative_increments

counter = [0, 150, 320, 480, 100, 290, 450, 610]
increments = cumulative_increments(counter, initial_zero_known=True)
display(pd.DataFrame({'counter_ml': counter, 'increment_ml': increments}))
print('Total across the two counter runs:', sum(increments), 'mL')
print('Final counter reading:', counter[-1], 'mL')
assert sum(increments) == 1090

,counter_ml,increment_ml
0,0,0
1,150,150
2,320,170
3,480,160
4,100,100
5,290,190
6,450,160
7,610,160


Total across the two counter runs: 1090 mL
Final counter reading: 610 mL


The final reading is 610 mL; the total across both runs is 1,090 mL. Those numbers should differ after a reset. A falling counter can also represent a correction, so automatic reset detection needs checking against device records.

If the first value has no known baseline, the volume before it is unknown. If a reading is missing, do not silently bridge the gap. Process each patient's device series separately and in timestamp order.

In [11]:
pd.DataFrame({
    'counter_ml': [150, 320, None, 480],
    'increment_ml': cumulative_increments([150, 320, None, 480])
})

,counter_ml,increment_ml
0,150.0,NaN
1,320.0,170.0
2,NaN,NaN
3,480.0,NaN


## 5. Separate missing data from zero

A blank fluid record does not show that no fluid was given. The fixture has both incomplete recording and a documented zero-intake case. Module 2 uses explicit coverage evidence to keep these states distinct.

A plausible range does not establish that a column is ready for analysis either. Check how many admissions have a value, not just the values that remain.

In [12]:
from datathon_prep.demo import check_column

examples = {
    'mostly_missing': pd.DataFrame({'value': [40, None, None, None, None]}),
    'empty_cohort': pd.DataFrame({'value': []}),
    'wrong_unit': pd.DataFrame({'value': [0.4, 0.5]}),
}
pd.DataFrame([check_column(frame, 'value', 21, 100) | {'example': name}
              for name, frame in examples.items()])

,column,rows,missing_fraction,out_of_range,status,example
0,value,5,0.8,0.0,REVIEW,mostly_missing
1,value,0,NaN,NaN,EMPTY,empty_cohort
2,value,2,0.0,2.0,REVIEW,wrong_unit


## Before moving on

Change the FiO₂ example to include a value with an unfamiliar unit. Explain why it should remain unclassified. Then inspect the two admissions for person 1 and explain what would happen if an update matched only on `person_id`.

For a real dataset, record the version, source concept, units, coverage and any transformation you used. Inspect missingness directly before excluding an anonymised date group; a date label alone does not establish a data-quality problem.

Continue with [Module 2](https://github.com/ReginaldCal/Digital-Critical-Care-Datathon-Prep/blob/main/module2_cohort_workflow.ipynb).

References: [OMOP concept conventions](https://ohdsi.github.io/CommonDataModel/cdm54.html#CONCEPT), [2026 datathon dictionary](https://github.com/AmsterdamUMC/AmsterdamUMCdb/blob/master/datathons/2026-01-esicm-datathon-colab/data-dictionary.csv), [BigQuery notebook parameters](https://googleapis.dev/python/bigquery-magics/latest/magics.html). Both the Python client and BigQuery notebook magic support parameterised queries.